/*
 * This file is generated by jOOQ.
 */
package com.libratrack.jooq.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class BookAuthors(
    val bookId: Int? = null,
    val authorId: Int? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: BookAuthors = other as BookAuthors
        if (this.bookId == null) {
            if (o.bookId != null)
                return false
        }
        else if (this.bookId != o.bookId)
            return false
        if (this.authorId == null) {
            if (o.authorId != null)
                return false
        }
        else if (this.authorId != o.authorId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.bookId == null) 0 else this.bookId.hashCode())
        result = prime * result + (if (this.authorId == null) 0 else this.authorId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("BookAuthors (")

        sb.append(bookId)
        sb.append(", ").append(authorId)

        sb.append(")")
        return sb.toString()
    }
}
