/*
 * This file is generated by jOOQ.
 */
package com.libratrack.jooq.tables


import com.libratrack.jooq.Public
import com.libratrack.jooq.keys.BOOK_AUTHORS_PKEY
import com.libratrack.jooq.keys.BOOK_AUTHORS__BOOK_AUTHORS_AUTHOR_ID_FKEY
import com.libratrack.jooq.keys.BOOK_AUTHORS__BOOK_AUTHORS_BOOK_ID_FKEY
import com.libratrack.jooq.tables.Authors.AuthorsPath
import com.libratrack.jooq.tables.Books.BooksPath
import com.libratrack.jooq.tables.records.BookAuthorsRecord

import java.util.function.Function

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row2
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.SelectField
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BookAuthors(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BookAuthorsRecord>?,
    parentPath: InverseForeignKey<out Record, BookAuthorsRecord>?,
    aliased: Table<BookAuthorsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BookAuthorsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.book_authors</code>
         */
        val BOOK_AUTHORS: BookAuthors = BookAuthors()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BookAuthorsRecord> = BookAuthorsRecord::class.java

    /**
     * The column <code>public.book_authors.book_id</code>.
     */
    val BOOK_ID: TableField<BookAuthorsRecord, Int?> = createField(DSL.name("book_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.book_authors.author_id</code>.
     */
    val AUTHOR_ID: TableField<BookAuthorsRecord, Int?> = createField(DSL.name("author_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<BookAuthorsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BookAuthorsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BookAuthorsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.book_authors</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.book_authors</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.book_authors</code> table reference
     */
    constructor(): this(DSL.name("book_authors"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BookAuthorsRecord>?, parentPath: InverseForeignKey<out Record, BookAuthorsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, BOOK_AUTHORS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class BookAuthorsPath : BookAuthors, Path<BookAuthorsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BookAuthorsRecord>?, parentPath: InverseForeignKey<out Record, BookAuthorsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<BookAuthorsRecord>): super(alias, aliased)
        override fun `as`(alias: String): BookAuthorsPath = BookAuthorsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): BookAuthorsPath = BookAuthorsPath(alias, this)
        override fun `as`(alias: Table<*>): BookAuthorsPath = BookAuthorsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<BookAuthorsRecord> = BOOK_AUTHORS_PKEY
    override fun getReferences(): List<ForeignKey<BookAuthorsRecord, *>> = listOf(BOOK_AUTHORS__BOOK_AUTHORS_BOOK_ID_FKEY, BOOK_AUTHORS__BOOK_AUTHORS_AUTHOR_ID_FKEY)

    private lateinit var _books: BooksPath

    /**
     * Get the implicit join path to the <code>public.books</code> table.
     */
    fun books(): BooksPath {
        if (!this::_books.isInitialized)
            _books = BooksPath(this, BOOK_AUTHORS__BOOK_AUTHORS_BOOK_ID_FKEY, null)

        return _books;
    }

    val books: BooksPath
        get(): BooksPath = books()

    private lateinit var _authors: AuthorsPath

    /**
     * Get the implicit join path to the <code>public.authors</code> table.
     */
    fun authors(): AuthorsPath {
        if (!this::_authors.isInitialized)
            _authors = AuthorsPath(this, BOOK_AUTHORS__BOOK_AUTHORS_AUTHOR_ID_FKEY, null)

        return _authors;
    }

    val authors: AuthorsPath
        get(): AuthorsPath = authors()
    override fun `as`(alias: String): BookAuthors = BookAuthors(DSL.name(alias), this)
    override fun `as`(alias: Name): BookAuthors = BookAuthors(alias, this)
    override fun `as`(alias: Table<*>): BookAuthors = BookAuthors(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BookAuthors = BookAuthors(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BookAuthors = BookAuthors(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BookAuthors = BookAuthors(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): BookAuthors = BookAuthors(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): BookAuthors = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): BookAuthors = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): BookAuthors = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): BookAuthors = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): BookAuthors = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): BookAuthors = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): BookAuthors = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): BookAuthors = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): BookAuthors = where(DSL.notExists(select))

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<Int?, Int?> = super.fieldsRow() as Row2<Int?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
