/*
 * This file is generated by jOOQ.
 */
package com.libratrack.jooq.tables.references


import com.libratrack.jooq.tables.Authors
import com.libratrack.jooq.tables.BookAuthors
import com.libratrack.jooq.tables.Books
import com.libratrack.jooq.tables.FlywaySchemaHistory



/**
 * The table <code>public.authors</code>.
 */
val AUTHORS: Authors = Authors.AUTHORS

/**
 * The table <code>public.book_authors</code>.
 */
val BOOK_AUTHORS: BookAuthors = BookAuthors.BOOK_AUTHORS

/**
 * The table <code>public.books</code>.
 */
val BOOKS: Books = Books.BOOKS

/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
